[2018-05-06 19:46:39,717] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:46:42,747] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline branching 2018-05-06T19:46:05.328571 --job_id 115 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-06 19:46:43,071] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:46:43,071] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-06 19:46:43,463] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:46:43,463] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:46:46,481] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:46:46,481] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:46:05.328571 [queued]>
[2018-05-06 19:46:46,486] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:46:46,486] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:46:05.328571 [queued]>
[2018-05-06 19:46:46,486] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:46:46,486] {models.py:1318} INFO - 
[2018-05-06 19:46:46,486] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:46:46,487] {base_task_runner.py:95} INFO - Subtask: Starting attempt 1 of 2
[2018-05-06 19:46:46,487] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:46:46,487] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-06 19:46:46,496] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:46:46,496] {models.py:1342} INFO - Executing <Task(BranchPythonOperator): branching> on 2018-05-06 19:46:05.328571
[2018-05-06 19:46:46,504] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:46:46,504] {models.py:1417} ERROR - 'str' object is not callable
[2018-05-06 19:46:46,504] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 19:46:46,505] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 19:46:46,505] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 19:46:46,505] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 105, in execute
[2018-05-06 19:46:46,505] {base_task_runner.py:95} INFO - Subtask:     branch = super(BranchPythonOperator, self).execute(context)
[2018-05-06 19:46:46,505] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 19:46:46,505] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 19:46:46,505] {base_task_runner.py:95} INFO - Subtask: TypeError: 'str' object is not callable
[2018-05-06 19:46:46,505] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:46:46,505] {models.py:1433} INFO - Marking task as UP_FOR_RETRY
[2018-05-06 19:46:46,511] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:46:46,511] {models.py:1462} ERROR - 'str' object is not callable
[2018-05-06 19:46:46,511] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-06 19:46:46,511] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-06 19:46:46,512] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2018-05-06 19:46:46,512] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/bin/airflow", line 28, in <module>
[2018-05-06 19:46:46,512] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2018-05-06 19:46:46,512] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/bin/cli.py", line 422, in run
[2018-05-06 19:46:46,512] {base_task_runner.py:95} INFO - Subtask:     pool=args.pool,
[2018-05-06 19:46:46,512] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/utils/db.py", line 53, in wrapper
[2018-05-06 19:46:46,513] {base_task_runner.py:95} INFO - Subtask:     result = func(*args, **kwargs)
[2018-05-06 19:46:46,513] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/models.py", line 1374, in run
[2018-05-06 19:46:46,513] {base_task_runner.py:95} INFO - Subtask:     result = task_copy.execute(context=context)
[2018-05-06 19:46:46,513] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 105, in execute
[2018-05-06 19:46:46,513] {base_task_runner.py:95} INFO - Subtask:     branch = super(BranchPythonOperator, self).execute(context)
[2018-05-06 19:46:46,513] {base_task_runner.py:95} INFO - Subtask:   File "/Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/operators/python_operator.py", line 80, in execute
[2018-05-06 19:46:46,513] {base_task_runner.py:95} INFO - Subtask:     return_value = self.python_callable(*self.op_args, **self.op_kwargs)
[2018-05-06 19:46:46,513] {base_task_runner.py:95} INFO - Subtask: TypeError: 'str' object is not callable
[2018-05-06 19:46:47,759] {jobs.py:2083} INFO - Task exited with return code 1
[2018-05-06 19:50:01,949] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:50:29,688] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:50:32,694] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run PropertyClassification_test_pipeline branching 2018-05-06T19:46:05.328571 --job_id 118 --raw -sd /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py']
[2018-05-06 19:50:33,026] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:50:33,026] {__init__.py:57} INFO - Using executor SequentialExecutor
[2018-05-06 19:50:33,427] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:50:33,426] {models.py:167} INFO - Filling up the DagBag from /Users/sam/All-Program/App/PropertyClassification/dags/test_pipeline.py
[2018-05-06 19:50:36,360] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:50:36,359] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:46:05.328571 [queued]>
[2018-05-06 19:50:36,365] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:50:36,364] {models.py:1126} INFO - Dependencies all met for <TaskInstance: PropertyClassification_test_pipeline.branching 2018-05-06 19:46:05.328571 [queued]>
[2018-05-06 19:50:36,365] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:50:36,365] {models.py:1318} INFO - 
[2018-05-06 19:50:36,365] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:50:36,365] {base_task_runner.py:95} INFO - Subtask: Starting attempt 2 of 2
[2018-05-06 19:50:36,365] {base_task_runner.py:95} INFO - Subtask: --------------------------------------------------------------------------------
[2018-05-06 19:50:36,365] {base_task_runner.py:95} INFO - Subtask: 
[2018-05-06 19:50:36,373] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:50:36,373] {models.py:1342} INFO - Executing <Task(BranchPythonOperator): branching> on 2018-05-06 19:46:05.328571
[2018-05-06 19:50:36,380] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:50:36,380] {python_operator.py:81} INFO - Done. Returned value was: create_overlaid_images
[2018-05-06 19:50:36,380] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:50:36,380] {python_operator.py:106} INFO - Following branch create_overlaid_images
[2018-05-06 19:50:36,381] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:50:36,380] {python_operator.py:107} INFO - Marking other directly downstream tasks as skipped
[2018-05-06 19:50:36,385] {base_task_runner.py:95} INFO - Subtask: [2018-05-06 19:50:36,385] {python_operator.py:119} INFO - Done.
[2018-05-06 19:50:36,390] {base_task_runner.py:95} INFO - Subtask: /Users/sam/App-Setup/anaconda/envs/anaconda35/lib/python3.5/site-packages/airflow/ti_deps/deps/base_ti_dep.py:94: PendingDeprecationWarning: generator '_get_dep_statuses' raised StopIteration
[2018-05-06 19:50:36,390] {base_task_runner.py:95} INFO - Subtask:   for dep_status in self._get_dep_statuses(ti, session, dep_context):
[2018-05-06 19:50:37,702] {jobs.py:2083} INFO - Task exited with return code 0
